name: 'Delete Github Cache'
description: 'Action to clean the github cache'
author: 'Jontze <dev@jontze.com>'
inputs:
  token:
    required: true
    description: Github token with read and write access to the target repository
  keys:
    required: true
    description: Target cache key
  repo:
    required: false
    description: Target repository
  limit:
    required: false
    description: GB limit - the action will start to delete cache entries only if the limit is exceeded
runs:
  using: 'node16'
  main: 'dist/index.js'
